export const strings = {
  en: {
    // Client Dashboard
    clientDashboard: "Client Dashboard",
    welcome: "Welcome",
    weddingInfo: "Wedding Information",
    groomName: "Groom's Name",
    groomParents: "Groom's Parents",
    brideName: "Bride's Name",
    brideParents: "Bride's Parents",
    date: "Date",
    venue: "Event Location",
    detectMyLocation: "Detect My Location",
    headingFont: "Heading Font",
    bodyFont: "Preview Font",
    headingPreview: "Heading Preview",
    bodyPreview: "Body preview text",
    khHeadingPreview: "មើលជាមុននូវចំណងជើង",
    khBodyPreview: "មើលការបង្ហាញអត្ថបទជាមុន",
    save: "Save",
    addGuest: "Add Guest",
    guestName: "Guest Name",
    guestNamePlaceholder: "Guest Name",
    guestList: "Guest List",
    name: "Name",
    invitationLink: "Invitation Link",
    viewInvite: "View Invite",
    logout: "Logout",
    locationDetected: "Location detected!",
    failedToDetectLocation: "Failed to detect location.",
    geolocationNotSupported: "Geolocation not supported.",
    weddingInfoUpdated: "Wedding info updated!",
    guestAdded: "Guest added!",

    // Invitation Page
    youAreInvitedToTheWeddingOf: "You are invited to the wedding of",
    and: "and",
    parentsOfGroom: "Son of Mr. \u0026 Mrs.",
    parentsOfBride: "Daughter of Mr. \u0026 Mrs.",
    receptionAt: "Reception to be held at",
    rsvp: "RSVP",
    attending: "Attending",
    notAttending: "Not Attending",
    submit: "Submit",
    thankYouForRsvping: "Thank you for your RSVP!",
    liveRsvpCount: "Live RSVP Count",
    peopleAttending: "people are attending",
  },
  kh: {
    // Client Dashboard
    clientDashboard: "ផ្ទាំងគ្រប់គ្រងអតិថិជន",
    welcome: "សូមស្វាគមន៍",
    weddingInfo: "ព័ត៌មានអាពាហ៍ពិពាហ៍",
    groomName: "ឈ្មោះកូនកំលោះ",
    groomParents: "ឪពុកម្តាយកូនកំលោះ",
    brideName: "ឈ្មោះកូនក្រមុំ",
    brideParents: "ឪពុកម្តាយកូនក្រមុំ",
    date: "កាលបរិច្ឆេទ",
    venue: "ទីកន្លែង",
    detectMyLocation: "ស្វែងរកទីតាំងរបស់ខ្ញុំ",
    headingFont: "ពុម្ពអក្សរចំណងជើង",
    bodyFont: "ពុម្ពអក្សរអត្ថបទ",
    headingPreview: "មើលជាមុននូវចំណងជើង",
    bodyPreview: "មើលការបង្ហាញអត្ថបទជាមុន",
    khHeadingPreview: "មើលជាមុននូវចំណងជើង",
    khBodyPreview: "មើលការបង្ហាញអត្ថបទជាមុន",
    save: "រក្សាទុក",
    addGuest: "បញ្ចូលឈ្មោះ",
    guestName: "ឈ្មោះភ្ញៀវ",
    guestNamePlaceholder: "សូមបញ្ចូលឈ្មោះ",
    guestList: "បញ្ជី​ឈ្មោះ​ភ្ញៀវ",
    name: "ឈ្មោះ",
    invitationLink: "តំណភ្ជាប់ការអញ្ជើញ",
    viewInvite: "មើលការអញ្ជើញ",
    logout: "ចាកចេញ",
    locationDetected: "បានរកឃើញទីតាំង!",
    failedToDetectLocation: "ការរកទីតាំងបានបរាជ័យ។",
    geolocationNotSupported: "មិនគាំទ្រទីតាំងភូមិសាស្ត្រទេ។",
    weddingInfoUpdated: "ព័ត៌មានអាពាហ៍ពិពាហ៍បានធ្វើបច្ចុប្បន្នភាព!",
    guestAdded: "បានបន្ថែមភ្ញៀវ!",

    // Invitation Page
    youAreInvitedToTheWeddingOf: "សូមគោរពអញ្ជើញចូលរួមក្នុងពិធីមង្គលការរបស់",
    and: "និង",
    parentsOfGroom: "កូនប្រុសរបស់លោក និងលោកស្រី",
    parentsOfBride: "កូនស្រីរបស់លោក និងលោកស្រី",
    receptionAt: "ពិធីទទួលភ្ញៀវនឹងប្រព្រឹត្តទៅនៅ",
    rsvp: "ការឆ្លើយតប",
    attending: "នឹង​ចូលរួម",
    notAttending: "មិន​ចូលរួម",
    submit: "ដាក់ស្នើ",
    thankYouForRsvping: "សូមអរគុណសម្រាប់ការឆ្លើយតបរបស់អ្នក!",
    liveRsvpCount: "ការរាប់ RSVP ផ្ទាល់",
    peopleAttending: "នាក់កំពុងចូលរួម",
  }
};
